### ISSUE TITLE
`extra_ttl` issue when creating instance of `NB2WLightCurveProduct`

### ISSUE THREAD

**Issue by burnout87** [oda-hub/dispatcher-plugin-nb2workflow#111]
When completing (locally) the [lightcurve](https://gitlab.renkulab.io/astronomy/mmoda/jemx-expert/-/blob/main/lightcurve.ipynb?ref_type=heads) notebook of jemx_expert, the following issue:

"__init__() got an unexpected keyword argument 'extra_ttl'"

when trying to create an instance of the class `NB2WLightCurveProduct` here:

https://github.com/oda-hub/dispatcher-plugin-nb2workflow/blob/94c316c0f980ba1e73116fd2e0be6a6ed4e9d9f0/dispatcher_plugin_nb2workflow/products.py#L86-L97

is some adjustments to the class needed?

EDIT: to mention, if I remove the label extra annotation, the exception does not appear

**Comment by dsavchenko** [comment]
I didn't manage to reproduce it locally

**Comment by burnout87** [comment]
which notebook are you running?

**Comment by dsavchenko** [comment]
`NB2WProduct` class needs to be adapted to accept `extra_ttl`. 
To think of taking `oda:label` into account. The simplest way is to set the product name to the label content. But it may affect usability of result in `oda_api` (having long names for properties)
