### ISSUE TITLE
fetch output notebook and return it as necessary, especially if there is an exception

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-plugin-nb2workflow#16]
# Advances Domain

Mention the Domain this issue addresses, e.g.: 

* UX
* resilience
* community-expanding feature

**Comment by dsavchenko** [comment]
This issue requires changes to the main dispatcher code. 
Therefore, let's decide on where the notebook should be in the output.
1 option: as an additional field in the `exit_status` dictionary
2 option: besides `analysis_parameters` and `api_code` in the `products` dictionary
The first option requires fewer changes. 
In both cases, something like `output_notebook` will be too specific to the plugin, probably we can use some more generic term.

**Comment by dsavchenko** [comment]
I see the way to get html of the output notebook from the backend. Seems it's enough.

But if we want the ipynb itself, is there an easy way to get it? @volodymyrss

**Comment by volodymyrss** [comment]
> I see the way to get html of the output notebook from the backend. Seems it's enough.
> 
> But if we want the ipynb itself, is there an easy way to get it? @volodymyrss

not sure, maybe we can add in nb2workflow

**Comment by dsavchenko** [comment]
> not sure, maybe we can add in nb2workflow

Then let's go the easy way now, using the HTML form, it will still be very useful as a debug tool. 
Do you have any advises on the schema?

**Comment by volodymyrss** [comment]
> > not sure, maybe we can add in nb2workflow
> 
> Then let's go the easy way now, using the HTML form, it will still be very useful as a debug tool. 

Ok, but I find it's extra useful to be able to re-run this failed notebook with some changes. It might take some extra effort to make this work e.g. with renku, so let's do html first.

> Do you have any advises on the schema?

Maybe it could be part of the output product list, just as another product. This could be done with the change to nb2workflow so that it adds it to output schema, then using some HTMLProduct type?

**Comment by dsavchenko** [comment]
> This could be done with the change to nb2workflow so that it adds it to output schema, then using some HTMLProduct type?

I don't think it's possible like this. 
If there is exception in the backend, the query status should be set to 'failed', in this case, no generic products are processed in the dispatcher, even if the response contains some (and I'm not sure if it's an easy change to return a result if the nb has failed).
That's why the html option is way easier, it could be fetched afterwards, regardless of the execution result.
