### ISSUE TITLE
test new parameter parsing on real data

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-plugin-nb2workflow#23]
following this https://github.com/oda-hub/dispatcher-app/pull/450#discussion_r966741674

to find if we have warnings in real life, detect them.

**Comment by dsavchenko** [comment]
As I wrote in PR, the warning can't be triggered with the current code

**Comment by volodymyrss** [comment]
so we determined it can be  triggered in principle, but I am not sure it is with the real output. is it? if yes, can we assert it in parsing? or if not, assert for no warning?

**Comment by volodymyrss** [comment]
we'll probably find other cases in the future when there is a warning
