### ISSUE TITLE
Is there functionality to pass messages/warnings etc.

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/dispatcher-plugin-nb2workflow#29]
@andriineronov is interested 

If notebook fails, the exception is in the response
If everything is ok, but we need to pass some warning/disclaimer/comment, is there some mechanism, or we can just agree on special output fields?

**Comment by volodymyrss** [comment]
Ok, if this way of expressing a message in the notebook makes sense, it can be implemented in the plugin, so I move it.
@dsavchenko please protest if necessary.

Once implemented, we add it to the guide https://github.com/oda-hub/hugo-odahub/issues/25
