### ISSUE TITLE
How to specify the restrictions on arguments?

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/dispatcher-plugin-nb2workflow#36]

**Comment by volodymyrss** [comment]
here is a proposal https://github.com/oda-hub/nb2workflow/pull/46 maybe there are better ideas

It assumes that the comment is "almost" pure ttl, the only modification is that "<http:...parameter> a " is assumed if it can be parsed this way.

```
emin=10 # oda:energyMin; oda:limits 3, 30
```

this also allows  workflow developers to slightly extend the ontology
