### ISSUE TITLE
(https://staging.odahub.fr/mmoda/): product list labels

### ISSUE THREAD

**Issue by andriineronov** [oda-hub/dispatcher-plugin-nb2workflow#62]
My notebook (for example, for Fermi/LAT analysis) returns a set of data products that are displayed as a list with buttons attached to view each data product. However, the names of the data products are not clear. Apparently sometimes they are the names to the variables that I assign in the "outputs" cell of the Notebook. However, at least for the first data product, the name appears to be empty. 
<img width="521" alt="image" src="https://github.com/oda-hub/mmoda-frontend-module/assets/27765790/9b0e8d73-d94a-41d4-8cb2-58d989d02877">

**Comment by dsavchenko** [comment]
This was just because of the old dispatcher image running on staging instance
