### ISSUE TITLE
How to return "spectrum" data product as an astropy table

### ISSUE THREAD

**Issue by andriineronov** [oda-hub/dispatcher-plugin-nb2workflow#65]
I tried to follow the advice of Denys and return the spectrum as an astropy table:
![image](https://github.com/oda-hub/dispatcher-plugin-nb2workflow/assets/27765790/0711497e-281b-4482-b126-9b79bb605a47)

when the service is deployed, this "spectrum" product is just ignored. I only get "picture" ......

**Comment by dsavchenko** [comment]
Is data an astropy table itself? 
You have to use ODAAstropyTable product, like in the example https://renkulab.io/gitlab/astronomy/mmoda/mmoda-nb2workflow-example/-/blob/master/notebooks/table.ipynb

**Comment by dsavchenko** [comment]
For such obvious cases we could think of doing it automatically in the backend https://github.com/oda-hub/nb2workflow/issues/97

**Comment by dsavchenko** [comment]
> Is `spec` an astropy table itself?
> You have to use ODAAstropyTable product, like in the example https://renkulab.io/gitlab/astronomy/mmoda/mmoda-nb2workflow-example/-/blob/master/notebooks/table.ipynb

@andriineronov please confirm if this is the case

**Comment by andriineronov** [comment]
Yes, it works now
