### ISSUE TITLE
use extra `return_progress` to return notebook

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-plugin-nb2workflow#74]
https://github.com/oda-hub/dispatcher-app/pull/601

**Comment by burnout87** [comment]
I am investigating to understand what are the steps that should be performed when using the `return_progress` arg, to return the execution status of the notebook and I have a first question:
are those the same as the ones of `run_query` (within the NB2WDataDispatcher class) ? or is there something else I should take into account? @dsavchenko @volodymyrss

**Comment by burnout87** [comment]
> the structure of the nb2w plugin is generally the same as of the others, I don't see any pecularities in this context.


thanks, I was more talking about the steps to be performed in order to return the current status of the notebook (which happens inside the newly introduced method `get_progress_run`)

**Comment by burnout87** [comment]
@dsavchenko @volodymyrss I still need to get those information for the implementation of the `get_progress_run` function

**Comment by volodymyrss** [comment]
> @dsavchenko @volodymyrss I still need to get those information for the implementation of the `get_progress_run` function

You'd need to fetch information from the backend as provided by these endpoints:

https://github.com/oda-hub/nb2workflow/blob/4dc062f5ba7503a88b3c11946f66d148d5022eff/nb2workflow/service.py#L791-L824

**Comment by burnout87** [comment]
I don't really understand how I should use those endpoints, the input I should provide and the how to use the output they produce. A dedicated meeting will help
