### ISSUE TITLE
Instruments disappear from available on staging

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/dispatcher-plugin-nb2workflow#78]
Transient issue
To investigate

**Comment by volodymyrss** [comment]
Let us know if we can help, describe the problem here if you want.

**Comment by dsavchenko** [comment]
More extended description:

The bot registers nb2workflow-based instrument in kg, properly deploys backend and does plugin reloading by calling "reload-plugin" endpoint. For some time, the instrument seems to function. But then it simply disappears from the list of available instruments, so run_analysis request will fail (as well as meta-data request). Seems that (this is to confirm) once the instrument disappears, it won't be available until the plugin reload (reload fixes the situation for some time). 

I'm also not 100% sure, but seems that this issue appears for one instruments but not the others. 

I haven't been able to reproduce this in the local debugging session. The corresponding Sentry entries don't contain useful additional information, and I can't find useful info in the logs either. (I inspect the raw output, though, the staging is not currently connected to the logstash.)

**Comment by dsavchenko** [comment]
I have a new hypothesis.

The `instr_factory_list` is constructed in the `exposer.py` of plugin when importing it with the `importer` module. Then it's static. That's why we need a `reload-plugin` endpoint, otherwise the list wouldn't be updated when the new instrument appears in the knowledge graph. 

But when we run dispatcher in container, multiple processes are started with gunicorn, so the reloading only affects one process, in others the list is not updated so dispatcher knows nothing about the new instrument. This explains why the instrument is sometimes available in some requests. 


The way around would be that `instr_factory_list` is not really a list, but rather a list-like iterable object which reads the kg every time. Besides the overall complexity of this approach, the main downside is yet another overhead. 

@volodymyrss @burnout87 if you have any ideas, let me know !
