### ISSUE TITLE
error parsing specific character

### ISSUE THREAD

**Issue by burnout87** [oda-hub/dispatcher-plugin-nb2workflow#79]
When calling the `parse_extra_triples` function, and the `extra_triples` arg passed is `\n, it crashes. The line where the crash happens is:

https://github.com/oda-hub/dispatcher-plugin-nb2workflow/blob/54e1e1507ab685c77d4c967d21ead6958cfa1ead/dispatcher_plugin_nb2workflow/queries.py#L41

with `rdflib==5.0.0`, if the library is upgraded at the latest version, it works

**Comment by dsavchenko** [comment]
I have also noticed that I use `unique` keyword here https://github.com/oda-hub/dispatcher-app/blob/e8f5b28e1f99f40e6efced9e438cc93a11d878cf/cdci_data_analysis/analysis/ontology.py#L124 
that's not available before `rdflib==6.2.0`. So the version needs to be restricted anyway.
